# Generated by Django 4.1.3 on 2022-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelling_from', models.CharField(choices=[('mumbai', 'MUMBAI'), ('delhi', 'DELHI'), ('bangalore', 'BANGALORE'), ('chennai', 'CHENNAI'), ('kolkata', 'KOLKATA')], default='delhi', max_length=9)),
                ('travelling_to', models.CharField(choices=[('mumbai', 'MUMBAI'), ('delhi', 'DELHI'), ('bangalore', 'BANGALORE'), ('chennai', 'CHENNAI'), ('kolkata', 'KOLKATA')], default='mumbai', max_length=9)),
                ('date_of_travelling', models.DateField(default='07-12-2022')),
                ('number_of_passengers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='bookingitems',
        ),
    ]
