# Generated by Django 4.1.3 on 2022-12-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_post_delete_bookingitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
