# Generated by Django 4.1.3 on 2022-12-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_bookingitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_passengers',
            field=models.IntegerField(max_length=2),
        ),
    ]
