# Generated by Django 4.1.3 on 2022-12-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_alter_post_number_of_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Mymodel',
        ),
    ]
