# Generated by Django 4.1.3 on 2022-12-07 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_rename_post_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitems',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
